#EDPS 845 A2, Mingying Zheng
# Lots O' Tests

## Overview

In this activity we'll collaborate on some code for reading, manipulating, and analyzing data from a lot of tests. The data come from subsets of items administered within the PISA 2009 study, where the tests are actually test booklets. You don't need to know anything about the study. The data come from the R package equate, though we'll write and then read them as text files, for fun.

This file is located in the github repo for the course. Once you've synced your local version of the project, you'll have access to it. You should write a separate R script containing the code necessary to solve the problems below. Save your script with a file extension ".R" inside the directory edps-845/in-class/R. Your file name isn't super important, but it should attempt to convey the functionality contained within the file.

## Data

Here we'll write the data sets as csv files. Each of these 13 files contains total scores for a group of students on four subtests. Some subtests differ by test, some are used across multiple tests.

```{r, eval = FALSE}
# Write 13 text files, one per test
library("equate")
for(i in 1:13)
  write.csv(PISA$totals[[i]], file = paste0("test", i, ".csv"))
```

Note that the equate package already contains the PISA data in R. Again, we're pretending that's not the case, at least in exercise 1 below. You will however use the other PISA data sets contained in the equate package. In equate, `PISA` is a list containing multiple data sets. As shown above, the total scores for the 13 tests are contained in `PISA$totals`.

## Exercises

#Here are the different issues we need to address, with some tips on how you might go about writing R code to address them. The goal here is to read the data into R, prep and clean them up, analyze them, and compile results into a report.

#1. Read in the 13 data files, storing each one as a data frame, with R object names `test1` through `test13`. Rather than write the code out for each test, use a loop. See the `assign()` function as a way of programmatically naming your 13 R objects.

test1 <- read.csv("C:/Users/Zheng/Desktop/Summer 2016/EDPS 845 R/edps-845/in-class/test1.csv")
View(test1)

setwd("C:/Users/Zheng/Desktop/Summer 2016/EDPS 845 R/edps-845/in-class/")
                
for(i in 1:13)
  assign(paste0("test", i), read.csv(paste0("test", i, ".csv"), row.names = 1))

 
2. Prep the data for analysis. Run a frequency table on every variable and summarize the results, noting any unexpected values, and the counts of missings by subtest and test.

names(test1)
names(test2)
names(test3)
names(test4)
names(test5)
names(test6)
names(test7)
names(test8)
names(test9)
names(test10)
names(test11)
names(test12)
names(test13)

lapply(PISA$totals, ncol)
lapply(test1, ncol)
lapply(PISA$totals, nrow)
names(PISA)
apply(PISA,1, sum) # 1 is the first dimension of the data, row.
apply(tempdat,2, mean) # 2 is the second dimension of the data

3. Append a new column to each data set that contains the school id for the student. The row names in each test data set correspond to the row names in the PISA data set, PISA$students. This data set contains the `PISA$students$schoolid` variable. Get frequency distributions for each test so as to examine numbers of students by school by test.

4. Find descriptives for each test and subtest by school. Collate the results into a snazzy table using either `knitr::kable()` or `xtable::xtable()`. Descriptives can be obtained with `epmr::dstudy()`.

5. Find descriptives and internal consistency reliabilities for each subtest, by test, and collate them into another nice table. Your table should also summarize results by subject area. Reliabilities can be obtained with `epmr::rstudy()`.

6. We know that any test administered in written form will require, to some extent, reading ability, though the test itself may not be intended to measure reading ability. We also know that science often involves some amount of math ability. Use linear models to examine the relationships between science, as a dependent variable, and math and reading, as independent variables. Note that only 6 of the 13 tests contain a math, reading, and science subtest. If a test contains more than one subtest in a subject area, choose one. Summarize results across these 6 tests.